#!/usr/bin/python3

import readline

import traceback

import argparse
import sqlite3

import os.path
import time

import shlex # THIS IS WONDERFUL

from commands import *

# Copied directly from SO #287871
class Cols:
	HEADER = '\033[95m'
	OKBLUE = '\033[94m'
	OKGREEN = '\033[92m'
	WARNING = '\033[93m'
	FAIL = '\033[91m'
	ENDC = '\033[0m'
	BOLD = '\033[1m'
	UNDERLINE = '\033[4m'

class SitDatabase:
	def __init__(self, conn):
		self.conn = conn
	def generate_tables(self):
		c = self.conn.cursor()
		c.execute('''
			CREATE TABLE IF NOT EXISTS projects (
				projname TEXT PRIMARY KEY,
				name TEXT
			);
		''')
		c.execute('''
			CREATE TABLE IF NOT EXISTS tasks (
				projname TEXT NOT NULL,
				taskname TEXT NOT NULL,

				FOREIGN KEY(projname) REFERENCES projects(projname),
				PRIMARY KEY (projname, taskname)
			);
		''')
		c.execute('''
			CREATE TABLE IF NOT EXISTS persons (
				username TEXT PRIMARY KEY,
				name TEXT,

				curr_projname TEXT,
				curr_taskname TEXT,

				FOREIGN KEY(curr_projname)
				REFERENCES projects(projname),
				FOREIGN KEY(curr_taskname)
				REFERENCES tasks(taskname)
			);
		''')
		c.execute('''
			CREATE TABLE IF NOT EXISTS activities (
				projname TEXT NOT NULL,
				taskname TEXT NOT NULL,
				activ_id INTEGER,

				name TEXT,

				FOREIGN KEY(projname) REFERENCES projects(projname),
				FOREIGN KEY(taskname) REFERENCES tasks(taskname),
				PRIMARY KEY (projname, taskname, activ_id)
			);
		''')
		c.execute('''
			CREATE TABLE IF NOT EXISTS hours (
				projname TEXT NOT NULL,
				taskname TEXT NOT NULL,
				hours_id INTEGER,

				activ_id INTEGER,
				assoc_user TEXT,

				start_time INTEGER,
				end_time INTEGER,

				FOREIGN KEY(activ_id) REFERENCES activities(activ_id),
				FOREIGN KEY(assoc_user) REFERENCES persons(username),

				FOREIGN KEY(projname) REFERENCES projects(projname),
				FOREIGN KEY(taskname) REFERENCES tasks(taskname),
				PRIMARY KEY (projname, taskname, hours_id)
			);
		''')
		self.conn.commit()
		print("sit: Executed table generation")
	def add_person(self, username):
		c = self.conn.cursor()
		inputs = (username,)
		c.execute('INSERT INTO persons (username) VALUES (?)', inputs)
		self.conn.commit()
		pass
	def add_project(self, projname):
		c = self.conn.cursor()
		inputs = (projname,)
		c.execute('INSERT INTO projects (projname) VALUES (?)', inputs)
		self.conn.commit()
		pass
	def add_task(self, projname, taskname):
		c = self.conn.cursor()
		# Get ID for task
		inputs = (projname, taskname,)
		c.execute('INSERT INTO tasks (projname, taskname) VALUES (?,?)', inputs)
		self.conn.commit()
	def start_clock(self, projname, taskname, username):
		c = self.conn.cursor()
		# Get ID for clock
		inputs = (projname, taskname)
		c.execute('''SELECT MAX(hours_id) AS id FROM hours
			WHERE projname=? AND taskname=?''', inputs)
		hours_id = 1
		last_hours_row = c.fetchone()
		if last_hours_row[0] is not None:
			hours_id = last_hours_row[0]+1
		# Perform INSERT
		start_time = time.time()
		inputs = (start_time, projname, taskname, hours_id, username)
		c.execute('''INSERT INTO hours
			(start_time, projname, taskname, hours_id, assoc_user)
			VALUES (?,?,?,?,?)''', inputs)
		self.conn.commit()
	def stop_clock(self, projname, taskname, username):
		c = self.conn.cursor()
		end_time  = time.time()
		inputs = (end_time, projname, taskname, username)
		c.execute('''UPDATE hours SET end_time=?
			WHERE projname=?
			AND taskname=?
			AND assoc_user=?
			AND end_time IS NULL
			''', inputs)
		self.conn.commit()
	def check_clock(self, projname, taskname, username):
		c = self.conn.cursor()
		inputs = (projname, taskname, username)
		# FETCH CURRENTLY TRACKING
		c.execute('''SELECT start_time FROM hours
			WHERE projname=?
			AND taskname=?
			AND assoc_user=?
			AND end_time IS NULL''', inputs)
		tracking = []
		for row in c.fetchall():
			datum = {}
			datum['start_time'] = row[0]
			tracking.append(datum)
		# FETCH READY-TO-LOG
		c.execute('''SELECT start_time, end_time FROM hours
			WHERE projname=?
			AND taskname=?
			AND assoc_user=?
			AND end_time IS NOT NULL
			AND activ_id IS NULL''', inputs)
		ready = []
		for row in c.fetchall():
			datum = {}
			datum['start_time'] = row[0]
			datum['end_time'] = row[1]
			ready.append(datum)
		return (tracking, ready)
	def apply_activity(self, projname, taskname, username, message):
		c = self.conn.cursor()
		# Get ID for activity
		inputs = (projname, taskname)
		c.execute('''SELECT MAX(activ_id) AS id FROM activities
			WHERE projname=? AND taskname=?''', inputs)
		activ_id = 1
		last_hours_row = c.fetchone()
		if last_hours_row[0] is not None:
			activ_id = last_hours_row[0]+1
		# Create the activity
		inputs = (projname, taskname, activ_id, message)
		c.execute('''INSERT INTO activities
			(projname, taskname, activ_id, name)
			VALUES (?,?,?,?)
			''', inputs)
		# Set activity to all unset hours
		inputs = (activ_id, projname, taskname, username)
		c.execute('''UPDATE hours SET activ_id=?
			WHERE projname=?
			AND taskname=?
			AND assoc_user=?
			AND end_time IS NOT NULL
			AND activ_id IS NULL
			''', inputs)
		self.conn.commit()

	def save_user_proj(self, username, projname):
		c = self.conn.cursor()
		inputs = (projname, username)
		c.execute('''UPDATE persons SET curr_projname=?
			WHERE username=?
			''', inputs)
		self.conn.commit()
	def save_user_task(self, username, projname, taskname):
		c = self.conn.cursor()
		inputs = (projname, taskname, username)
		c.execute('''UPDATE persons SET
			curr_projname=?,
			curr_taskname=?
			WHERE username=?
			''', inputs)
		self.conn.commit()

	def load_user(self, username):
		c = self.conn.cursor()
		# Get ID for clock
		inputs = (username,)
		c.execute('''SELECT curr_projname, curr_taskname FROM persons
			WHERE username=?''', inputs)
		row = c.fetchone()
		data = {}
		data['projname'] = row[0]
		data['taskname'] = row[1]
		return data

	def check_proj_exists(self, projname):
		c = self.conn.cursor()
		# Get ID for clock
		inputs = (projname,)
		c.execute('''SELECT * FROM projects
			WHERE projname=?''', inputs)
		return len(c.fetchall()) > 0
	def check_task_exists(self, projname, taskname):
		c = self.conn.cursor()
		# Get ID for clock
		inputs = (projname,taskname,)
		c.execute('''SELECT * FROM tasks
			WHERE projname=? AND taskname=?''', inputs)
		return len(c.fetchall()) > 0

	def fetch_tasks(self, projname):
		c = self.conn.cursor()
		# Get ID for clock
		inputs = (projname,)
		c.execute('''SELECT taskname FROM tasks
			WHERE projname=?''', inputs)
		data = []
		for row in c.fetchall():
			datum = {}
			datum['taskname'] = row[0]
			data.append(datum)
		return data

	def fetch_projects(self):
		c = self.conn.cursor()
		# Get ID for clock
		# inputs = ()
		c.execute('''SELECT projname FROM projects
			WHERE 1=1''')
		data = []
		for row in c.fetchall():
			datum = {}
			datum['projname'] = row[0]
			data.append(datum)
		return data

class SitSession:
	def __init__(self, db):
		self.props = {}
		self.db = db
		# default properties
		self.props['user'] = None
		self.props['project'] = None
		self.props['task'] = None
	def set_db(self):
		self.db = db
	def get_db(self):
		return self.db
	def set_prop(self, key, val):
		self.props[key] = val
	def get_prop(self, key):
		return self.props[key]
	def require(self, key):
		if self.props[key] is None:
			raise CommandException("No "+key+" selected")
		return self.props[key]

class SitOperator:
	def __init__(self, sess):
		self.sess = sess
		self.s = None
	def run(self):

		scf = SitCommandFactory(self.sess)
		self.s = scf.get_sit()

		while True:
			dirln = Cols.WARNING + "NULL" + Cols.ENDC
			project = self.sess.get_prop("project")
			task = self.sess.get_prop("task")
			if project is not None:
				dirln = Cols.OKGREEN
				dirln += project + Cols.ENDC
			if task is not None:
				dirln += ":"
				dirln += Cols.OKBLUE
				dirln += task + Cols.ENDC
			# print(dirln+"> ", end='')
			cmd = input(dirln+"> ")
			if cmd == "exit":
				break
			try:
				self.do(cmd)
			except CommandException as e:
				print(str(e))
			except Exception as e:
				traceback.print_exc()
			else:
				pass

	def do(self, cmd):
		args = shlex.split(cmd)
		self.s.run(args)
		pass

def main(fn):
	newFile = True
	if (os.path.isfile(fn)):
		newFile = False

	conn = sqlite3.connect(fn)
	db = SitDatabase(conn)

	db.generate_tables()

	p = SitOperator(SitSession(db))
	p.run()


parser = argparse.ArgumentParser(description='Log work history to file.')
parser.add_argument('filename', type=str)
args = parser.parse_args()

fn = args.filename
main(fn)

# conn = sqlite3.connect('test.db')

# c = conn.cursor()
